// Unity Build Uber File generated by CMake
// This file is auto generated, do not manually edit it.

#include <StdAfx.h>
#include <E:/Code/GameAPI/Code/GamePlugin.cpp>
#include <E:/Code/GameAPI/Code/IGameAPI.cpp>
#include <E:/Code/GameAPI/Code/GameAPIBridge.cpp>

