; Listing generated by Microsoft (R) Optimizing Compiler Version 19.13.26128.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\PC-3\AppData\Local\Temp\.NETFramework,Version=v4.0.AssemblyAttributes.cpp"
